### ISSUE TITLE
An internal error occurred during: "Organizing includes".

### ISSUE THREAD

**Issue by lostcontrol** [wangzw/CppStyle#27]
Since I upgraded to the latest version (1.5.0.0), I get NPE every time I call the organize includes operation.
```
java.lang.NullPointerException
	at org.wangzw.plugin.cppstyle.ClangFormatFormatter.getSourceFilePath(ClangFormatFormatter.java:77)
	at org.wangzw.plugin.cppstyle.ClangFormatFormatter.format(ClangFormatFormatter.java:135)
	at org.eclipse.cdt.core.formatter.CodeFormatter.format(CodeFormatter.java:116)
	at org.eclipse.cdt.internal.formatter.ChangeFormatter.formatChangedCode(ChangeFormatter.java:100)
	at org.eclipse.cdt.internal.ui.refactoring.includes.IncludeOrganizer.organizeIncludes(IncludeOrganizer.java:331)
	at org.eclipse.cdt.internal.ui.editor.OrganizeIncludesAction$1.run(OrganizeIncludesAction.java:89)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

eclipse.buildId=4.7.1.M20171009-0410
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.cpp.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.cpp.product

**Comment by lostcontrol** [comment]
Just noticed that this breaks other features like "Source -> Implement Method..."

**Comment by wangzw** [comment]
Seems duplicated with #25 

Please try to upgrade CppStyle with update site ```http://www.cppstyle.com/update``` by remove it and reinstall since I did not bump version number.

I have merged the patch yesterday.

**Comment by lostcontrol** [comment]
Yes, definitely. Sorry, will try, thanks!

**Comment by lostcontrol** [comment]
Mmhhh... didn't work

**Comment by lostcontrol** [comment]
Ok, my fault, I was lazy and did not restart Eclipse between deinstall and reinstall. The jar is from yesterday.

**Comment by lostcontrol** [comment]
Yeeeaahhhh!!!! Had to remove the jar, fix artifacts.xml and eventually managed to reinstall cppstyle properly. Working now, thanks.
