### ISSUE TITLE
Format on source menu entries

### ISSUE THREAD

**Issue by schulmar** [wangzw/CppStyle#8]
Some source menu entries like "Implement Method ... " trigger a formatter call for the newly inserted code.

Using CppStyle under Eclipse Mars "Implement Method" triggers the error:

> Plug-in "org.wangzw.cppstyle" was unable to instantiate class "org.wangzw.plugin.cppstyle.CppCodeFormatter".

```
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Display.error(Display.java:1186)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:765)
	at org.eclipse.swt.widgets.Display.getSystemColor(Display.java:2138)
	at org.wangzw.plugin.cppstyle.CppCodeFormatter.setupConsoleStream(CppCodeFormatter.java:613)
	at org.wangzw.plugin.cppstyle.CppCodeFormatter.<init>(CppCodeFormatter.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.cdt.core.ToolFactory.createCodeFormatter(ToolFactory.java:56)
	at org.eclipse.cdt.internal.formatter.ChangeFormatter.formatChangedCode(ChangeFormatter.java:98)
	at org.eclipse.cdt.internal.core.dom.rewrite.changegenerator.ChangeGenerator.generateChange(ChangeGenerator.java:117)
	at org.eclipse.cdt.internal.core.dom.rewrite.changegenerator.ChangeGenerator.generateChange(ChangeGenerator.java:104)
	at org.eclipse.cdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.rewriteAST(ASTRewriteAnalyzer.java:26)
	at org.eclipse.cdt.core.dom.rewrite.ASTRewrite.rewriteAST(ASTRewrite.java:212)
	at org.eclipse.cdt.internal.ui.refactoring.ModificationCollector.createFinalChange(ModificationCollector.java:85)
	at org.eclipse.cdt.internal.ui.refactoring.CRefactoring.createChange(CRefactoring.java:177)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:124)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:209)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:87)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

IIRC you used the currently active editor to determin the path of the file that is currently being formatted. Unfortunately, this is not sufficient for many applications of the formatter, like mass formatting or formatting after automatic source transformations.

I stumbled into the same problem when I implemented my own [clang-format plugin](https://github.com/schulmar/clang_format_eclipsecdt). Maybe [some of the code there](https://github.com/schulmar/clang_format_eclipsecdt/blob/master/net.github.clang_format_cdt/src/net/github/clang_formateclipse/Formatter.java#L140) is of use to you.

**Comment by wangzw** [comment]
Thanks, I will check this on this weekend.

**Comment by wangzw** [comment]
fixed
